import { z } from 'zod';
import { resourceSpecSchema } from './common.js';

/**
 * Node command specs for the managed-resource primitives (v2): databases,
 * object storage, serverless functions, CI runners, and autoscaling. These are
 * mirrored by the Rust agent as serde structs and executed via the Docker
 * Engine API with least privilege — still no arbitrary shell.
 */

/* --------------------------------- Databases -------------------------------- */

export const databaseEngineSchema = z.enum(['postgres', 'mysql', 'redis', 'mongodb']);

export const provisionDatabaseSpecSchema = z.object({
  databaseId: z.string(),
  engine: databaseEngineSchema,
  version: z.string().default('16'),
  containerName: z.string(),
  /** Initial database name (ignored for redis). */
  dbName: z.string().default('app'),
  username: z.string().default('yourstack'),
  /** Generated by the control plane, transmitted over TLS only. */
  password: z.string(),
  storageMb: z.number().int().positive().default(10_240),
  resources: resourceSpecSchema,
  port: z.number().int().positive(),
  networkName: z.string().optional(),
});
export type ProvisionDatabaseSpec = z.infer<typeof provisionDatabaseSpecSchema>;

export const stopDatabaseSpecSchema = z.object({ databaseId: z.string(), containerName: z.string() });
export const removeDatabaseSpecSchema = z.object({
  databaseId: z.string(),
  containerName: z.string(),
  removeVolume: z.boolean().default(false),
});
export const backupDatabaseSpecSchema = z.object({
  databaseId: z.string(),
  containerName: z.string(),
  engine: databaseEngineSchema,
  /** Bucket to store the dump in, if configured. */
  bucketId: z.string().optional(),
});

/* --------------------------------- Storage ---------------------------------- */

export const provisionStorageSpecSchema = z.object({
  bucketId: z.string(),
  bucketName: z.string(),
  containerName: z.string(),
  /** MinIO root credentials (S3-compatible), TLS-transmitted. */
  accessKey: z.string(),
  secretKey: z.string(),
  quotaMb: z.number().int().positive().default(51_200),
  isPublic: z.boolean().default(false),
  port: z.number().int().positive(),
  consolePort: z.number().int().positive().optional(),
});
export type ProvisionStorageSpec = z.infer<typeof provisionStorageSpecSchema>;

export const removeStorageSpecSchema = z.object({
  bucketId: z.string(),
  containerName: z.string(),
  removeVolume: z.boolean().default(false),
});

/* -------------------------------- Functions --------------------------------- */

export const functionRuntimeSchema = z.enum(['node20', 'python311', 'go122', 'bun1']);

export const deployFunctionSpecSchema = z.object({
  functionId: z.string(),
  name: z.string(),
  runtime: functionRuntimeSchema,
  /** Entrypoint, e.g. "index.handler". */
  handler: z.string().default('index.handler'),
  /** Source bundle: gzipped tar (base64) or a git ref. */
  source: z.discriminatedUnion('kind', [
    z.object({ kind: z.literal('inline'), code: z.string() }),
    z.object({ kind: z.literal('bundle'), tarballBase64: z.string() }),
    z.object({ kind: z.literal('git'), repoUrl: z.string().url(), ref: z.string(), cloneToken: z.string().optional() }),
  ]),
  env: z.record(z.string(), z.string()).default({}),
  memoryMb: z.number().int().positive().max(4096).default(256),
  timeoutMs: z.number().int().positive().max(900_000).default(30_000),
  containerName: z.string(),
  port: z.number().int().positive(),
  /** Minimum warm instances (0 = scale-to-zero). */
  minInstances: z.number().int().nonnegative().default(0),
});
export type DeployFunctionSpec = z.infer<typeof deployFunctionSpecSchema>;

export const invokeFunctionSpecSchema = z.object({
  functionId: z.string(),
  containerName: z.string(),
  payload: z.record(z.string(), z.unknown()).default({}),
});

export const removeFunctionSpecSchema = z.object({ functionId: z.string(), containerName: z.string() });

/* --------------------------------- Runners ---------------------------------- */

export const registerRunnerSpecSchema = z.object({
  runnerId: z.string(),
  poolId: z.string(),
  /** GitHub Actions self-hosted runner registration token (short-lived). */
  registrationToken: z.string(),
  /** Repo or org URL the runner attaches to. */
  githubUrl: z.string().url(),
  labels: z.array(z.string()).default(['yourstack', 'self-hosted']),
  containerName: z.string(),
  /** Ephemeral runner: exits after one job (recommended for isolation). */
  ephemeral: z.boolean().default(true),
});
export type RegisterRunnerSpec = z.infer<typeof registerRunnerSpecSchema>;

export const deregisterRunnerSpecSchema = z.object({ runnerId: z.string(), containerName: z.string() });

/* ------------------------------- Autoscaling -------------------------------- */

export const scaleAppSpecSchema = z.object({
  appId: z.string(),
  containerName: z.string(),
  /** Desired replica count computed by the control-plane autoscaler. */
  replicas: z.number().int().nonnegative(),
  /** Per-replica resource envelope. */
  resources: resourceSpecSchema,
});
export type ScaleAppSpec = z.infer<typeof scaleAppSpecSchema>;

/* ----------------------------- Scheduled jobs (v3) -------------------------- */

/** Run a container to completion (cron job / one-off task). */
export const runJobSpecSchema = z.object({
  jobId: z.string(),
  runId: z.string(),
  containerName: z.string(),
  image: z.string().min(1),
  command: z.array(z.string()).optional(),
  env: z.record(z.string(), z.string()).default({}),
  resources: resourceSpecSchema,
  /** Kill the job if it runs longer than this. */
  timeoutMs: z.number().int().positive().default(600_000),
  registryAuth: z.string().optional(),
});
export type RunJobSpec = z.infer<typeof runJobSpecSchema>;

/* --------------------------- v4: networking + node ops ---------------------- */

export const firewallRuleSpecSchema = z.object({
  direction: z.enum(['inbound', 'outbound']).default('inbound'),
  action: z.enum(['allow', 'deny']).default('allow'),
  protocol: z.enum(['tcp', 'udp', 'icmp', 'any']).default('tcp'),
  /** Port or range, e.g. "443" or "8000-9000". Empty = any. */
  port: z.string().optional(),
  /** CIDR source/destination, e.g. "0.0.0.0/0" or "10.0.0.0/8". */
  cidr: z.string().default('0.0.0.0/0'),
  comment: z.string().optional(),
});
export type FirewallRuleSpec = z.infer<typeof firewallRuleSpecSchema>;

/** Apply a firewall ruleset to a node (nftables/ufw under the hood). */
export const configureFirewallSpecSchema = z.object({
  firewallId: z.string(),
  /** Default policy for inbound traffic not matched by a rule. */
  defaultInbound: z.enum(['allow', 'deny']).default('deny'),
  defaultOutbound: z.enum(['allow', 'deny']).default('allow'),
  rules: z.array(firewallRuleSpecSchema).max(200),
});
export type ConfigureFirewallSpec = z.infer<typeof configureFirewallSpecSchema>;

export const lbTargetSpecSchema = z.object({
  /** Backend address, e.g. "10.0.0.5:8080" or a container name. */
  address: z.string(),
  weight: z.number().int().positive().default(1),
});

/** Provision a load balancer (Caddy/HAProxy) fronting a set of backends. */
export const provisionLbSpecSchema = z.object({
  loadBalancerId: z.string(),
  containerName: z.string(),
  listenPort: z.number().int().positive(),
  algorithm: z.enum(['round_robin', 'least_conn', 'ip_hash']).default('round_robin'),
  targets: z.array(lbTargetSpecSchema).min(1),
  /** Optional domain + auto-HTTPS termination. */
  domain: z.string().optional(),
  autoHttps: z.boolean().default(false),
  healthPath: z.string().default('/'),
  sticky: z.boolean().default(false),
});
export type ProvisionLbSpec = z.infer<typeof provisionLbSpecSchema>;

export const removeLbSpecSchema = z.object({ loadBalancerId: z.string(), containerName: z.string() });

/** Node-administration commands (typed — never arbitrary shell). */
export const nodeRebootSpecSchema = z.object({ delaySeconds: z.number().int().nonnegative().default(5) });
export const dockerPruneSpecSchema = z.object({
  images: z.boolean().default(true),
  volumes: z.boolean().default(false),
  buildCache: z.boolean().default(true),
});
export const agentUpdateSpecSchema = z.object({
  /** Version/channel to update the agent to. */
  version: z.string().default('latest'),
  downloadUrl: z.string().url().optional(),
});
